# Generated by Django 3.2.6 on 2022-01-05 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220105_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 1, 5, 8, 51, 16, 460390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 5, 8, 51, 16, 460413, tzinfo=utc)),
        ),
    ]
