# Generated by Django 3.2.6 on 2022-01-09 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220108_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['value']},
        ),
        migrations.AddField(
            model_name='post',
            name='hero_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='hero_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(blank=True, default='0.5x0.5', editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 1, 9, 8, 45, 10, 356438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 9, 8, 45, 10, 356486, tzinfo=utc)),
        ),
    ]
